#!/usr/bin/env bash
# Configue ufw so that it blocks all incoming traffic, except the TCP port 22, 80, 443
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
